### ISSUE TITLE
Kubernetes Deployment fails due to invalid env variables

### ISSUE THREAD

**Issue by schemen** [TheAxelander/OpenBudgeteer#79]
When deploying to kubernetes, you run into problems as the env variables have an invalid spec. Essentially, you cannot use any `:` in env variables.

Example:
```
        - name: 'Connection:Password'
          valueFrom:
            secretKeyRef:
              name: budgeteer-secrets
              key: db_password
```

Will lead to 
```
* spec.template.spec.containers[0].env[0].name: Invalid value: "Connection:Password": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')
```

I would suggest using more common methods of declaring variables, like `MYSQL_PASSWORD`

Cheers

**Comment by TheAxelander** [comment]
Will be covered with #71

**Comment by tvories** [comment]
@schemen I was able to get around this by mounting a config map to the container. 

```yaml
apiVersion: v1
kind: configmap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  appsettings.json |-
    {
      "Connection": {
        "Provider" :  "mysql", 
        "Database": "mysql",
        "Server": "mysql",
        "Port": "3306",
        "User": "openbudgeteer",
        "Password": "openbudgeteer-pw"
      },
      "AppSettings": {
        "Culture": "en-US"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }
```
